I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/combat.rpy", line 2, in script
    python:
  File "game/combat.rpy", line 180, in <module>
    combat_loop()
  File "game/combat.rpy", line 149, in combat_loop
    active_character.pick_move_player()
  File "game/combat.rpy", line 59, in pick_move_player
    tempList.append((i.label, i.name))
AttributeError: 'Attack' object has no attribute 'label'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/combat.rpy", line 2, in script
    python:
  File "D:\Fragmented-main\Fragmented-main\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Fragmented-main\Fragmented-main\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/combat.rpy", line 180, in <module>
    combat_loop()
  File "game/combat.rpy", line 149, in combat_loop
    active_character.pick_move_player()
  File "game/combat.rpy", line 59, in pick_move_player
    tempList.append((i.label, i.name))
AttributeError: 'Attack' object has no attribute 'label'

Windows-10-10.0.19044 AMD64
Ren'Py 8.1.3.23091805
Fragmented 1.0
Wed Oct 25 14:21:07 2023
