I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/combat.rpy", line 2, in script
    python:
  File "game/combat.rpy", line 214, in <module>
    renpy.jump(introduction_ranger)
NameError: name 'introduction_ranger' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/combat.rpy", line 2, in script
    python:
  File "D:\Git-Huh\Fragmented\Fragmented\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Git-Huh\Fragmented\Fragmented\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/combat.rpy", line 214, in <module>
    renpy.jump(introduction_ranger)
NameError: name 'introduction_ranger' is not defined

Windows-10-10.0.22635 AMD64
Ren'Py 8.1.3.23091805
Fragmented 1.0
Sun Oct 29 17:32:31 2023
