I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script4.rpy", line 192, in script
    jump path_to_hell_with_assistant
ScriptError: could not find label 'path_to_hell_with_assistant'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script4.rpy", line 192, in script
    jump path_to_hell_with_assistant
  File "D:\Git-Huh\Fragmented\renpy-8.1.3-sdk\renpy\ast.py", line 1992, in execute
    rv = renpy.game.script.lookup(target)
  File "D:\Git-Huh\Fragmented\renpy-8.1.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'path_to_hell_with_assistant'.

Windows-10-10.0.22635 AMD64
Ren'Py 8.1.3.23091805
Fragmented 1.0
Tue Dec  5 21:14:27 2023
